version: "3.7"
services:
  front_end:
    build:
      context: .
      dockerfile: ./front_end/docker/Dockerfile
    volumes:
      - ./front_end/src:/front_end/src
      - ./front_end/public:/front_end/public
    restart: always
    ports:
      - ${CLIENT_PUBLIC_PORT}:4000

  back_end:
    build:
      context: .
      dockerfile: ./back_end/docker/Dockerfile
    volumes:
      - ./back_end/src:/back_end/src
    restart: always
    ports:
      - ${SERVER_PUBLIC_PORT}:3000